services:
  app:
    image: 'cloud-storage:v1.4'
    build:
      context: .
    ports:
      - "8080:8080"
    container_name: cloud-storage-container
    depends_on:
      - db
      - minio
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/cloud_storage_db
      - SPRING_DATASOURCE_USERNAME=cloud_storage_db
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:16'
    container_name: db-postgres-container
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=cloud_storage_db
      - POSTGRES_PASSWORD=123
    volumes:
      - db_data:/var/lib/postgresql/data

  minio:
    image: 'minio/minio'
    container_name: minio-container
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: root
      MINIO_SECRET_KEY: rootroot
    volumes:
      - minio_data:/data

  redis:
    image: 'redis:latest'
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
  minio_data:

